#TUPLES ARE SIMILAR TO LISTS OR ARRAYS IN PYTHON IT CAN BE CREATED BUT CANNOT BE MODIFIED OR DELETED,
# LET'S TAKE AN EXAMPLE IN ORDER TO UNDERSTAND THE TOPIC CLEARLY

numbers = (1,2,3,4)
print(numbers[0])
numbers[0] = 2      #HERE ITS SHOWING ERROR AS I AM TRYING TO MODIFY THE VALUE OF TUPLE